# Generated by Django 4.2.4 on 2023-08-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampsiteApp', '0002_alter_bookingrecord_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingrecord',
            options={'managed': False},
        ),
    ]
