# Generated by Django 4.2.4 on 2023-08-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampsiteApp', '0004_alter_bookingrecord_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrecord',
            old_name='arrivalDate',
            new_name='arrival_Date',
        ),
        migrations.RenameField(
            model_name='bookingrecord',
            old_name='depatureDate',
            new_name='depature_Date',
        ),
    ]
